import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/topNav";
import { Icons } from "@/lib/icons";

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` container mx-auto lg:flex flex-10 font-fira-code ${firaCode.variable}   antialiased`}
      >
        <div className="flex-1 bg-[#282C33]   h-screen hidden lg:flex flex-col justify-between">
          <div className="flex flex-col items-center justify-center gap-4">
            <div className="border-l border-[#ABB2BF] h-64"></div>

            <div className="flex flex-col gap-2">
              <Icons.GitHub />
              <Icons.LinkedIn />
              <Icons.Twiter />
              <Icons.Instagram />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4  place-items-center px-16 ">
            {[...Array(10).keys()].map((index) => (
              <div
                key={index}
                className="h-1 w-1 bg-[#ABB2BF] rounded-full"
              ></div>
            ))}
          </div>
          <div></div>
          <div></div>
        </div>
        <div className="flex-8 bg-[#282C33] ">
          <TopNav />
          {children}
        </div>
        <div className="flex-1  bg-[#282C33]  h-screen hidden lg:flex flex-col justify-between  items-end">
          <div></div>
          <div className="h-28 w-20 border-l border-t border-b border-[#ABB2BF]"></div>
          <div></div>
        </div>
      </body>
    </html>
  );
}
